redis:
    address: 127.0.0.1:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
api_key: APID8LynJKrhDzo
api_secret: 7RcURNf1t5jMaJOfB5yDeP3Rvz1XL8VXRWeEP3WSATvA
ws_url: wss://livekit-vyom.indusnettechnologies.com
bind_address: 0.0.0.0
rtmp_port: 1935
whip_port: 8080
http_relay_port: 9090
logging:
    json: false
    level: ""
development: false
rtc_config:
    udp_port: 7885
    use_external_ip: true
    enable_loopback_candidate: false
